#define INICIO              257
#define FIN                 258
#define LEER                259
#define ESCRIBIR            260
#define SI                  261
#define ENTONCES            262
#define SI_NO               263
#define FIN_SI              264
#define MIENTRAS            265
#define HACER               266
#define FIN_MIENTRAS        267
#define REPETIR             268
#define HASTA_QUE           269
#define PARA                270
#define DESDE               271
#define HASTA               272
#define PASO                273
#define FIN_PARA            274
#define ASIGNACION          275
#define SUMA                276
#define RESTA               277
#define PRODUCTO            278
#define DIVISION            279
#define MODULO              280
#define POTENCIA            281
#define CONCATENACION       282
#define MENOR_QUE           283
#define MENOR_IGUAL_QUE     284
#define MAYOR_QUE           285
#define MAYOR_IGUAL_QUE     286
#define IGUAL               287
#define DISTINTO            288
#define DISYUNCION_LOGICA   289
#define CONJUNCION_LOGICA   290
#define NEGACION_LOGICA     291
#define FIN_SENTENCIA       292
#define PARENTESIS_INICIAL  293
#define PARENTESIS_FINAL    294
#define IDENTIFICADOR       295
#define CADENA              296
#define NUMERO              297
#define COMENTARIO          298
#define COMENTARIO_LINEA    299
