/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componente;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author rhorm
 */
public class componente extends javax.swing.JPanel {
    
    private int nivel;
    private String flag="Agua";
    /**
     * Creates new form componente
     */
    public componente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imagen = new javax.swing.JLabel();
        botonMas = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        botonAgua = new javax.swing.JButton();
        botonCafe = new javax.swing.JButton();
        botonServir = new javax.swing.JButton();

        setForeground(new java.awt.Color(204, 204, 204));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vaso0.png"))); // NOI18N
        imagen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonMas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha_arriba.png"))); // NOI18N
        botonMas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMasMouseClicked(evt);
            }
        });

        botonMenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/flecha_abajo.png"))); // NOI18N
        botonMenos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonMenos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMenosMouseClicked(evt);
            }
        });

        botonAgua.setBackground(new java.awt.Color(153, 204, 255));
        botonAgua.setText("Agua");
        botonAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonAguaMouseClicked(evt);
            }
        });

        botonCafe.setBackground(new java.awt.Color(127, 61, 0));
        botonCafe.setText("Café");
        botonCafe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCafeMouseClicked(evt);
            }
        });

        botonServir.setBackground(new java.awt.Color(255, 255, 255));
        botonServir.setText("Servir");
        botonServir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonServirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(botonAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonServir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonMenos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonServir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonMasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMasMouseClicked
        if(nivel<100)
            nivel+=25;
        setNivel(nivel);
    }//GEN-LAST:event_botonMasMouseClicked

    private void botonMenosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMenosMouseClicked
        if(nivel>0)
            nivel-=25;
        setNivel(nivel);
    }//GEN-LAST:event_botonMenosMouseClicked

    private void botonAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAguaMouseClicked
        flag="Agua";
        if(nivel!=0){
            nivel=0;
            setNivel(nivel);
        }
    }//GEN-LAST:event_botonAguaMouseClicked

    private void botonCafeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCafeMouseClicked
        flag="Cafe";
        if(nivel!=0){
            nivel=0;
            setNivel(nivel);
        }
    }//GEN-LAST:event_botonCafeMouseClicked

    private void botonServirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonServirMouseClicked
        if(nivel==0){
            JOptionPane.showMessageDialog(null, "Rellene el vaso para ser servido", "InfoBox: " + "Servicio", JOptionPane.INFORMATION_MESSAGE);
        }else{
            String vaso;
            if(flag.equals("Cafe")){
                vaso="café";
            }else{
                vaso="agua";
            }
            JOptionPane.showMessageDialog(null, "Su vaso de "+vaso+" se está sirviendo", "InfoBox: " + "Servicio", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_botonServirMouseClicked
    
    private void setNivel(int nivel){
        if(nivel==0)
            imagen.setIcon(new ImageIcon(getClass().getResource("/imagenes/vaso0.png")));   
        else
            imagen.setIcon(new ImageIcon(getClass().getResource("/imagenes/vaso"+flag+nivel+".png")));
    }
    
    public int getNivel(){
        return nivel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgua;
    private javax.swing.JButton botonCafe;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonServir;
    private javax.swing.JLabel imagen;
    // End of variables declaration//GEN-END:variables
}
