/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author rhorm
 */
public class Calculadora extends javax.swing.JFrame {

     private double operando1 = 0;
     private double operando2 = 0;
     private int flag = 0;
     private double aux = 0;
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Numero1 = new javax.swing.JButton();
        Numero2 = new javax.swing.JButton();
        Numero3 = new javax.swing.JButton();
        Numero4 = new javax.swing.JButton();
        Numero5 = new javax.swing.JButton();
        Numero7 = new javax.swing.JButton();
        Numero6 = new javax.swing.JButton();
        Numero8 = new javax.swing.JButton();
        Numero9 = new javax.swing.JButton();
        Numero0 = new javax.swing.JButton();
        suma = new javax.swing.JButton();
        resta = new javax.swing.JButton();
        multiplicacion = new javax.swing.JButton();
        division = new javax.swing.JButton();
        ClearAll = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        resultado = new javax.swing.JTextField();
        registro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 102, 255));
        setBounds(new java.awt.Rectangle(2, 1, 0, 0));
        setLocation(new java.awt.Point(125, 125));
        setLocationByPlatform(true);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setFocusable(false);
        jPanel1.setName(""); // NOI18N
        jPanel1.setNextFocusableComponent(resultado);
        jPanel1.setVerifyInputWhenFocusTarget(false);

        Numero1.setBackground(new java.awt.Color(51, 51, 255));
        Numero1.setText("1");
        Numero1.setFocusable(false);
        Numero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero1MouseClicked(evt);
            }
        });

        Numero2.setBackground(new java.awt.Color(51, 51, 255));
        Numero2.setText("2");
        Numero2.setFocusable(false);
        Numero2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero2MouseClicked(evt);
            }
        });

        Numero3.setBackground(new java.awt.Color(51, 51, 255));
        Numero3.setText("3");
        Numero3.setFocusable(false);
        Numero3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero3MouseClicked(evt);
            }
        });

        Numero4.setBackground(new java.awt.Color(51, 51, 255));
        Numero4.setText("4");
        Numero4.setFocusable(false);
        Numero4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero4MouseClicked(evt);
            }
        });

        Numero5.setBackground(new java.awt.Color(51, 51, 255));
        Numero5.setText("5");
        Numero5.setFocusable(false);
        Numero5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero5MouseClicked(evt);
            }
        });

        Numero7.setBackground(new java.awt.Color(51, 51, 255));
        Numero7.setText("7");
        Numero7.setFocusable(false);
        Numero7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero7MouseClicked(evt);
            }
        });

        Numero6.setBackground(new java.awt.Color(51, 51, 255));
        Numero6.setText("6");
        Numero6.setFocusable(false);
        Numero6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero6MouseClicked(evt);
            }
        });

        Numero8.setBackground(new java.awt.Color(51, 51, 255));
        Numero8.setText("8");
        Numero8.setFocusable(false);
        Numero8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero8MouseClicked(evt);
            }
        });

        Numero9.setBackground(new java.awt.Color(51, 51, 255));
        Numero9.setText("9");
        Numero9.setFocusable(false);
        Numero9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero9MouseClicked(evt);
            }
        });

        Numero0.setBackground(new java.awt.Color(51, 51, 255));
        Numero0.setText("0");
        Numero0.setFocusable(false);
        Numero0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Numero0MouseClicked(evt);
            }
        });

        suma.setBackground(new java.awt.Color(51, 51, 255));
        suma.setText("+");
        suma.setFocusable(false);
        suma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sumaMouseClicked(evt);
            }
        });

        resta.setBackground(new java.awt.Color(51, 51, 255));
        resta.setText("-");
        resta.setFocusable(false);
        resta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                restaMouseClicked(evt);
            }
        });

        multiplicacion.setBackground(new java.awt.Color(51, 51, 255));
        multiplicacion.setText("*");
        multiplicacion.setFocusable(false);
        multiplicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiplicacionMouseClicked(evt);
            }
        });

        division.setBackground(new java.awt.Color(51, 51, 255));
        division.setText("/");
        division.setFocusable(false);
        division.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisionMouseClicked(evt);
            }
        });

        ClearAll.setBackground(new java.awt.Color(51, 51, 255));
        ClearAll.setText("CL");
        ClearAll.setFocusable(false);
        ClearAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearAllMouseClicked(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(51, 51, 255));
        Clear.setText("C");
        Clear.setFocusable(false);
        Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearMouseClicked(evt);
            }
        });

        igual.setBackground(new java.awt.Color(51, 51, 255));
        igual.setText("=");
        igual.setFocusable(false);
        igual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                igualMouseClicked(evt);
            }
        });

        resultado.setEditable(false);
        resultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        resultado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        resultado.setText("0");
        resultado.setActionCommand("<Not Set>");
        resultado.setFocusable(false);

        registro.setEditable(false);
        registro.setFocusable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Numero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Numero4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Numero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Numero5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Numero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(division, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(resultado, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(registro, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(registro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suma, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resta, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Numero7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Numero9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(division, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(Numero0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Numero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero1MouseClicked
        putNumber(1);
    }//GEN-LAST:event_Numero1MouseClicked

    private void Numero2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero2MouseClicked
        putNumber(2);
    }//GEN-LAST:event_Numero2MouseClicked

    private void Numero3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero3MouseClicked
        putNumber(3);
    }//GEN-LAST:event_Numero3MouseClicked

    private void Numero4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero4MouseClicked
        putNumber(4);
    }//GEN-LAST:event_Numero4MouseClicked

    private void Numero5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero5MouseClicked
        putNumber(5);
    }//GEN-LAST:event_Numero5MouseClicked

    private void Numero6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero6MouseClicked
        putNumber(6);
    }//GEN-LAST:event_Numero6MouseClicked

    private void Numero7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero7MouseClicked
        putNumber(7);
    }//GEN-LAST:event_Numero7MouseClicked

    private void Numero8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero8MouseClicked
        putNumber(8);
    }//GEN-LAST:event_Numero8MouseClicked

    private void Numero9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero9MouseClicked
        putNumber(9);
    }//GEN-LAST:event_Numero9MouseClicked

    private void Numero0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Numero0MouseClicked
        putNumber(0);
    }//GEN-LAST:event_Numero0MouseClicked

    private void sumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sumaMouseClicked
        putOperation(1);
    }//GEN-LAST:event_sumaMouseClicked

    private void restaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_restaMouseClicked
        putOperation(2);
    }//GEN-LAST:event_restaMouseClicked

    private void multiplicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiplicacionMouseClicked
        putOperation(3);
    }//GEN-LAST:event_multiplicacionMouseClicked

    private void divisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisionMouseClicked
        putOperation(4);
    }//GEN-LAST:event_divisionMouseClicked

    private void igualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_igualMouseClicked
        igualdad();
    }//GEN-LAST:event_igualMouseClicked

    private void ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearMouseClicked
        if(resultado.getText().length()>0){
            resultado.setText(resultado.getText().substring(0,resultado.getText().length()-1));
        }
    }//GEN-LAST:event_ClearMouseClicked

    private void ClearAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearAllMouseClicked
        reset();
    }//GEN-LAST:event_ClearAllMouseClicked

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int code = evt.getKeyCode();
        if(code>=48 && code<=57){
            putNumber(code-48);
        }
        if(code >=96 && code <=105){
            putNumber(code-96);
        }
        if(code==521 || code==107 || code==43){
            putOperation(1);
        }
        if(code==45 || code==109){
            putOperation(2);
        }
        if(code==42 || code==106){
            putOperation(3);
        }
        if(code==47 || code==111){
            putOperation(4);
        }
        if(code==8){
           resultado.setText(resultado.getText().substring(0,resultado.getText().length()-1)); 
        }
        if(code==127){
           reset();
        }
        if(code==10){
            igualdad();
        }
    }//GEN-LAST:event_formKeyPressed
    private void putOperation(int operation){
        if(flag==5){
            reset();
        }
        if(!isNumeric(resultado.getText())){
            reset();
            resultado.setText("error");
        }else{
            if(flag!=0){
               operando2 = Double.parseDouble(resultado.getText());
               aux = operar(operando1, operando2);
            }
            operando1=Integer.parseInt(resultado.getText());
            switch(operation){
                case 1:
                    resultado.setText("+");
                    setRegistro(registro.getText()+"+");
                    flag=1;
                    break;
                case 2:
                    resultado.setText("-");
                    setRegistro(registro.getText()+"-");
                    flag=2;
                    break;
                case 3:
                    resultado.setText("*"); 
                    setRegistro(registro.getText()+"*");
                    flag=3;
                    break;
                case 4:
                    resultado.setText("/");  
                    setRegistro(registro.getText()+"/");
                    flag=4;
                    break;
            }
        }
    }
    private void putNumber(int number){
        if(isNumeric(resultado.getText()) && flag!=5 && Integer.parseInt(resultado.getText())!=0)
            resultado.setText(resultado.getText()+String.valueOf(number));
        else
            resultado.setText(String.valueOf(number));
        if(flag==5){
            flag=0;
            resetRegistro();
        }
        setRegistro(registro.getText()+String.valueOf(number));
    }
    private double operar(double op1, double op2){
        double res = 0;
        if(op1==0){
            return op2;
        }
        switch(flag){
            case 1:
                if(aux==0){
                    res = op1 + op2;
                }else{
                    res = aux + op2;
                }
                break;
            case 2:
                if(aux==0){
                    res = op1 - op2;
                }else{
                    res = aux - op2;
                }
                break;
            case 3:
                if(aux==0){
                    res = op1 * op2;
                }else{
                    res = aux * op2;
                }
                break;
            case 4:
               if(aux==0){
                    res = op1 / op2;
                }else{
                    res = aux / op2;
                }
        }
        aux = 0;
        return res;
    }
    
    private static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Double.parseDouble(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    
    private void reset(){
        resultado.setText("0");
        operando1=operando2=aux=0;
        flag=0;
    }
    
    private void setRegistro(String registro){
        this.registro.setText(registro);
    }
    
    private void resetRegistro(){
        this.registro.setText("");
    }
    
    private void igualdad(){
        operando2=Double.parseDouble(resultado.getText());
        String sol = String.valueOf(operar(operando1,operando2));
        reset();
        resultado.setText(sol);
        flag = 5;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton ClearAll;
    private javax.swing.JButton Numero0;
    private javax.swing.JButton Numero1;
    private javax.swing.JButton Numero2;
    private javax.swing.JButton Numero3;
    private javax.swing.JButton Numero4;
    private javax.swing.JButton Numero5;
    private javax.swing.JButton Numero6;
    private javax.swing.JButton Numero7;
    private javax.swing.JButton Numero8;
    private javax.swing.JButton Numero9;
    private javax.swing.JButton division;
    private javax.swing.JButton igual;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton multiplicacion;
    private javax.swing.JTextField registro;
    private javax.swing.JButton resta;
    private javax.swing.JTextField resultado;
    private javax.swing.JButton suma;
    // End of variables declaration//GEN-END:variables
}
