/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package internacionalizacion;

import java.awt.event.KeyEvent;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.StringTokenizer;

/**
 *
 * @author rhorm
 */
public class internacionalizacion extends javax.swing.JFrame {
    /**
     * Creates new form internacionalizacion
     */
    private int flag = 0;
    public internacionalizacion() {
        initComponents();
        ResourceBundle rb = ResourceBundle.getBundle("internacionalizacion/Bundle", Locale.getDefault());
        fechaTexto.setDateFormatString(rb.getString("internacionalizacion.fechaTexto.dateFormatString"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        nombreTexto = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        cantidad = new javax.swing.JLabel();
        cantidadTexto = new javax.swing.JTextField();
        euro = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        espanol = new javax.swing.JButton();
        ingles = new javax.swing.JButton();
        libra = new javax.swing.JLabel();
        fechaTexto = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusable(false);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("internacionalizacion/Bundle"); // NOI18N
        nombre.setText(bundle.getString("internacionalizacion.nombre.text")); // NOI18N
        nombre.setFocusable(false);

        nombreTexto.setText(bundle.getString("internacionalizacion.nombreTexto.text")); // NOI18N

        buscar.setText(bundle.getString("internacionalizacion.buscar.text")); // NOI18N
        buscar.setFocusable(false);

        cantidad.setText(bundle.getString("internacionalizacion.cantidad.text")); // NOI18N
        cantidad.setFocusable(false);

        cantidadTexto.setText(bundle.getString("internacionalizacion.cantidadTexto.text_1")); // NOI18N
        cantidadTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadTextoKeyTyped(evt);
            }
        });

        euro.setText(bundle.getString("internacionalizacion.euro.text")); // NOI18N

        fecha.setText(bundle.getString("internacionalizacion.fecha.text")); // NOI18N
        fecha.setFocusable(false);

        espanol.setText(bundle.getString("internacionalizacion.espanol.text")); // NOI18N
        espanol.setFocusable(false);
        espanol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espanolActionPerformed(evt);
            }
        });

        ingles.setText(bundle.getString("internacionalizacion.ingles.text")); // NOI18N
        ingles.setFocusable(false);
        ingles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inglesActionPerformed(evt);
            }
        });

        libra.setText(bundle.getString("internacionalizacion.libra.text")); // NOI18N

        fechaTexto.setDateFormatString(bundle.getString("internacionalizacion.fechaTexto.dateFormatString")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(fecha)
                            .addGap(22, 22, 22))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cantidad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(libra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nombre)
                        .addGap(26, 26, 26)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cantidadTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(euro))
                    .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(espanol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ingles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(espanol)
                    .addComponent(cantidadTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidad)
                    .addComponent(euro)
                    .addComponent(libra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fecha)
                    .addComponent(ingles)
                    .addComponent(fechaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void espanolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espanolActionPerformed
        Locale aux = new Locale("es", "ES");
        if(!Locale.getDefault().equals(aux)){
            Locale.setDefault(aux);
            ResourceBundle rb = ResourceBundle.getBundle("internacionalizacion/Bundle", aux);
            convertirDivisa(rb);   
            fechaTexto.setDateFormatString(rb.getString("internacionalizacion.fechaTexto.dateFormatString"));
        }
    }//GEN-LAST:event_espanolActionPerformed

    private void inglesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inglesActionPerformed
        Locale aux = new Locale("en", "GB");
        if(!Locale.getDefault().equals(aux)){
            Locale.setDefault(aux);
            ResourceBundle rb = ResourceBundle.getBundle("internacionalizacion/Bundle", aux);
            convertirDivisa(rb);
            fechaTexto.setDateFormatString(rb.getString("internacionalizacion.fechaTexto.dateFormatString"));
        }
    }//GEN-LAST:event_inglesActionPerformed

    private void cantidadTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadTextoKeyTyped
        if(cantidadTexto.getText().equals("")){
            flag=0;
        }
        char numero = evt.getKeyChar();
        if(!(Character.isDigit(numero) || numero==KeyEvent.VK_BACK_SPACE || numero == KeyEvent.VK_DELETE || numero == KeyEvent.VK_PERIOD || numero == KeyEvent.VK_COMMA)){
            evt.consume();
        }
        if((numero == KeyEvent.VK_COMMA || numero == KeyEvent.VK_PERIOD)&& flag==0){
            flag=1;
        }else if((numero == KeyEvent.VK_COMMA || numero == KeyEvent.VK_PERIOD) && flag==1) {
            evt.consume();
        }
    }//GEN-LAST:event_cantidadTextoKeyTyped
    
    private void convertirDivisa(ResourceBundle rb){
        nombre.setText(rb.getString("internacionalizacion.nombre.text"));
        cantidad.setText(rb.getString("internacionalizacion.cantidad.text"));
        espanol.setText(rb.getString("internacionalizacion.espanol.text"));
        fecha.setText(rb.getString("internacionalizacion.fecha.text"));
        buscar.setText(rb.getString("internacionalizacion.buscar.text"));
        ingles.setText(rb.getString("internacionalizacion.ingles.text"));
        euro.setText(rb.getString("internacionalizacion.euro.text"));
        libra.setText(rb.getString("internacionalizacion.libra.text"));
        
        if(!cantidadTexto.getText().equals("")){
            StringTokenizer comas = new StringTokenizer(cantidadTexto.getText(),",");
            String antecoma = comas.nextToken();
            if(comas.hasMoreTokens()){
                cantidadTexto.setText(antecoma+"."+comas.nextToken());
            }
            if(isNumeric(cantidadTexto.getText())){
                double conversion = Double.parseDouble(cantidadTexto.getText());
                String numeroCadena;
                if(Locale.getDefault().equals(Locale.UK)){
                    conversion/=1.1348;
                }else{
                    conversion/=0.8812;
                }
                numeroCadena = String.valueOf(conversion);
                StringTokenizer tokens = new StringTokenizer(numeroCadena,".");
                String token1 = tokens.nextToken();
                String token2 = tokens.nextToken();
                if(!token2.equals("0")){
                    cantidadTexto.setText(token1+"."+token2.substring(0, 2));
                }else{
                    cantidadTexto.setText(token1);
                }
            }
        }
    }
    private static boolean isNumeric(String cadena) {

        boolean resultado;

        try {
            Double.parseDouble(cadena);
            resultado = true;
        } catch (NumberFormatException excepcion) {
            resultado = false;
        }

        return resultado;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(internacionalizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new internacionalizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JLabel cantidad;
    private javax.swing.JTextField cantidadTexto;
    private javax.swing.JButton espanol;
    private javax.swing.JLabel euro;
    private javax.swing.JLabel fecha;
    private com.toedter.calendar.JDateChooser fechaTexto;
    private javax.swing.JButton ingles;
    private javax.swing.JLabel libra;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreTexto;
    // End of variables declaration//GEN-END:variables
}
